<a href="https://colab.research.google.com/gist/Manojreddy-07/9c1cbec2fcc35142646ea26fa32d72fd/placement_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#developing a model which can predict the students placement based on the factors age,gender,stream,internships,cgpa,hostel,arrears
import numpy as np
import pandas as pd

LOGISTIC REGRESSION :
Regression means estimation and logistic regression algorithm used for predicting the dependent values based independent variables.Therefore the outcome must be a categorical or discrete value. It can be either Yes or No, 0 or 1, true or False, etc.Helpful in classification Problems.it has the ability to provide probabilities and classify new data using continuous and discrete datasets.The sigmoid function is a mathematical function used to map the predicted values to probabilities.
It maps any real value into another value within a range of 0 and 1.
The value of the logistic regression must be between 0 and 1, which cannot go beyond this limit, so it forms a curve like the "S" form. The S-form curve is called the Sigmoid function or the logistic function.


import all the necessary libraries

In [ ]:
df=pd.read_csv("college_Placements.csv")
df.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1

upload the csv file to the collab and read the data from the csv to collab using pandas inbuilt function read_csv().

In [ ]:
df['Gender'] = df['Gender'].apply(lambda x: 1 if x == 'Male' else 0)

# Mapping dictionary for Stream branches to numerical values
stream_mapping = {
    'Electronics And Communication': 0,
    'Computer Science': 1,
    'Information Technology': 2,
    'Mechanical': 3,
    'Electrical':4,
    'Civil':5
}
# Apply the mapping to the 'Stream' column
df['Stream'] = df['Stream'].map(stream_mapping)


As machine learning algorithms will accept only the numerical values or the binary representation ,iam gonna convert the gender column into '0's and '1's also stream column to the numericals.

In [ ]:
df

Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
0      22       1       0            1     8       1                  1   
1      21       0       1            0     7       1                  1   
2      22       0       2            1     6       0                  0   
3      21       1       2            0     8       0                  1   
4      22       1       3            0     8       1                  0   
...   ...     ...     ...          ...   ...     ...                ...   
2961   23       1       2            0     7       0                  0   
2962   23       1       3            1     7       1                  0   
2963   22       1       2            1     7       0                  0   
2964   22       1       1            1     7       0                  0   
2965   23       1       5            0     8       0                  0   

      PlacedOrNot  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
2961            0  
2962            0  
2963            0  
2964            0  
2965            1  

[2966 rows x 8 columns]

In [ ]:
df.shape

(2966, 8)

Shape will return the number of rows and columns present in the dataframe

In [ ]:
"""
0)preprocessing + EDA + feature Selection
1) Extract input and output cols
2)scale the values
3)train test split
4)train the model
5)evaluation/selection of model
6)deploy the model(not done)
"""
df.info()#prints the number of non-null values



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2966 non-null   int64
 1   Gender             2966 non-null   int64
 2   Stream             2966 non-null   int64
 3   Internships        2966 non-null   int64
 4   CGPA               2966 non-null   int64
 5   Hostel             2966 non-null   int64
 6   HistoryOfBacklogs  2966 non-null   int64
 7   PlacedOrNot        2966 non-null   int64
dtypes: int64(8)
memory usage: 185.5 KB


In [ ]:
df=df.iloc[:,1:]

describing the process for any machine learning model and info method returns the null values

In [ ]:
x = df.iloc[:,[0,1,2,3,4,5,6]]#ip :independent
y=df.iloc[:,-1]#op :dependent

Here we gonna separate our input columns(x) and output columns(y)

In [ ]:
x#separated input and output columns

Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
0          1       0            1     8       1                  1   
1          0       1            0     7       1                  1   
2          0       2            1     6       0                  0   
3          1       2            0     8       0                  1   
4          1       3            0     8       1                  0   
...      ...     ...          ...   ...     ...                ...   
2961       1       2            0     7       0                  0   
2962       1       3            1     7       1                  0   
2963       1       2            1     7       0                  0   
2964       1       1            1     7       0                  0   
2965       1       5            0     8       0                  0   

      PlacedOrNot  
0               1  
1               1  
2               1  
3               1  
4               1  
...           ...  
2961            0  
2962            0  
2963            0  
2964            0  
2965            1  

[2966 rows x 7 columns]

In [ ]:
y

0       1
1       1
2       1
3       1
4       1
       ..
2961    0
2962    0
2963    0
2964    0
2965    1
Name: PlacedOrNot, Length: 2966, dtype: int64

In [ ]:
print(x.shape)
print(y.shape)

(2966, 7)
(2966,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


This train_test_split Method will be useful for the splitting of training and testing data.
here training data taken (70%) and testing data(30%).

In [ ]:
x_train #70% for training of ip

Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
1685       1       1            0     8       0                  0   
2298       1       1            1     6       0                  0   
386        1       1            1     8       0                  0   
1222       1       3            0     7       1                  0   
1923       0       1            0     8       1                  0   
...      ...     ...          ...   ...     ...                ...   
1079       1       5            2     7       0                  0   
917        1       5            0     7       1                  0   
1065       1       0            1     8       0                  0   
1363       1       3            0     6       1                  0   
67         1       2            0     8       0                  0   

      PlacedOrNot  
1685            1  
2298            0  
386             1  
1222            0  
1923            1  
...           ...  
1079            0  
917             0  
1065            1  
1363            0  
67              1  

[2076 rows x 7 columns]

In [ ]:

y_train#30% for training of op

1685    1
2298    0
386     1
1222    0
1923    1
       ..
1079    0
917     0
1065    1
1363    0
67      1
Name: PlacedOrNot, Length: 2076, dtype: int64

In [ ]:



x_test#30% of ip

Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
2182       1       0            1     6       0                  1   
946        1       1            2     7       0                  0   
75         1       5            0     8       0                  0   
2423       1       4            0     7       0                  0   
2701       1       1            0     8       0                  1   
...      ...     ...          ...   ...     ...                ...   
1998       1       1            0     8       0                  0   
2066       1       2            2     6       0                  0   
2444       1       0            0     8       0                  0   
379        1       1            0     7       0                  1   
2773       1       4            1     8       0                  0   

      PlacedOrNot  
2182            1  
946             1  
75              1  
2423            0  
2701            1  
...           ...  
1998            1  
2066            1  
2444            1  
379             0  
2773            1  

[890 rows x 7 columns]

In [ ]:

y_test#30% of op

2182    1
946     1
75      1
2423    0
2701    1
       ..
1998    1
2066    1
2444    1
379     0
2773    1
Name: PlacedOrNot, Length: 890, dtype: int64

for the scaling the values in the range 0-1 use sklearn

In [ ]:
from sklearn.preprocessing import StandardScaler

the StandardScaler in scikit-learn is used to preprocess and standardize features by removing the mean and scaling them to unit variance. This helps ensure that features are on a similar scale, leading to improved performance and stability for various machine learning algorithms.

In [ ]:
scaler=StandardScaler()

In [ ]:
x_train=scaler.fit_transform(x_train)

After this line of code, your x_train variable will contain the standardized features, where each feature has a mean of 0 and a standard deviation of 1.

Keep in mind that when using a StandardScaler (or any other preprocessing technique), you should apply the same transformation to your testing data (x_test) as well. This ensures that your testing data is processed in the same way as your training data to maintain consistency.

In [ ]:
x_train

array([[ 0.44488502, -0.74564544, -0.94763888, ..., -0.60926358,
        -0.48474651,  0.88689056],
       [ 0.44488502, -0.74564544,  0.38431665, ..., -0.60926358,
        -0.48474651, -1.12753483],
       [ 0.44488502, -0.74564544,  0.38431665, ..., -0.60926358,
        -0.48474651,  0.88689056],
       ...,
       [ 0.44488502, -1.3987931 ,  0.38431665, ..., -0.60926358,
        -0.48474651,  0.88689056],
       [ 0.44488502,  0.56064987, -0.94763888, ...,  1.64132574,
        -0.48474651, -1.12753483],
       [ 0.44488502, -0.09249779, -0.94763888, ..., -0.60926358,
        -0.48474651,  0.88689056]])

In [ ]:
x_test=scaler.transform(x_test)

In [ ]:
x_test

array([[ 0.44488502, -1.3987931 ,  0.38431665, ..., -0.60926358,
         2.06293388,  0.88689056],
       [ 0.44488502, -0.74564544,  1.71627217, ..., -0.60926358,
        -0.48474651,  0.88689056],
       [ 0.44488502,  1.86694518, -0.94763888, ..., -0.60926358,
        -0.48474651,  0.88689056],
       ...,
       [ 0.44488502, -1.3987931 , -0.94763888, ..., -0.60926358,
        -0.48474651,  0.88689056],
       [ 0.44488502, -0.74564544, -0.94763888, ..., -0.60926358,
         2.06293388, -1.12753483],
       [ 0.44488502,  1.21379752,  0.38431665, ..., -0.60926358,
        -0.48474651,  0.88689056]])

After performing the scaling then all the values are in the same in range so thats its easier for finding the optimal solution.

it also prevents data dominancy while if algorithm wants to find the distance between the features so that larger values cannot dominate and bias.
When features are on different scales, it becomes challenging to assess their relative contributions.

In summary, scaling helps ensure that your machine learning algorithms work effectively, converge efficiently, and produce better results by removing the influence of differing feature scales.

In [ ]:
#Evaluation/selecting the model
from sklearn.linear_model import LogisticRegression#importing the LR

In [ ]:
clf=LogisticRegression()#create a object logistic regression algorithm

In [ ]:
#train the model
clf.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_test_predict=clf.predict(x_test)#30% of input(x_test) expects to have 30% of output(y_test)
y_test_predict

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,

now predict method will predict the corresponding out and store it in the variable y_test_predict which is our model predicted
values(model output) and then we will compare with y_test(actual output) to calculate the accuracy.

In [ ]:
y_test

2182    1
946     1
75      1
2423    0
2701    1
       ..
1998    1
2066    1
2444    1
379     0
2773    1
Name: PlacedOrNot, Length: 890, dtype: int64

using predict method from Logistic regression class ,it is going to fetch the output and stored in variable 'y_test_predict'.

In [ ]:
from sklearn.metrics import accuracy_score

from sklearn.metrics module import the accuracy score function,which takes the two parameters explained in next cell.

In [ ]:
accuracy_score(y_test_predict,y_test)#accuracy of testing data prediction

1.0

Here the two parameters one denotes the actual output and other is our model output.Both are cross checked by the function accuracy_score and finally
produces upto what extent of values are matching.Similary samething is performed for the training data as folllows.
Accuracy score will describe how efficient our model in predicting the output values

In [ ]:
y_train_predict=clf.predict(x_train)#70% ip expected to have 70% output
y_train_predict

array([1, 0, 1, ..., 1, 0, 1])

In [ ]:
y_train

1685    1
2298    0
386     1
1222    0
1923    1
       ..
1079    0
917     0
1065    1
1363    0
67      1
Name: PlacedOrNot, Length: 2076, dtype: int64

In [ ]:
accuracy_score(y_train,y_train_predict)#accuracy for the training data

1.0

In [ ]:
#clf.predict([[22,1,0,1,8,1,1]])#to predict individual row

after predicting the output for the training data and we ensure that our model performing well and good as its producing the output :1.0 also for testing data as well